version: '3.7'

services:
    portainer:
        image: portainer/portainer:alpine
        ports:
            - 9998:9000
            - 9999:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    cah_backend:
        container_name: 'cah_backend'
        build:
            context: ./backend
            target: be-development
        volumes:
            - be-reserved:/var/app/node_modules
            - ./backend/app:/var/app/app
        ports:
            - 10001:3000

    cah_backend_deployment:
        container_name: 'cah_backend'
        build:
            context: ./backend
            target: be-deployment
        ports:
            - 10001:3000

    cah_frontend:
        container_name: 'cah_frontend'
        build:
            context: ./frontend
            target: fe-development
        volumes:
            - ./frontend:/var/app/
            - fe-reserved-nm:/var/app/node_modules
            - fe-reserved-dist:/var/app/dist
        ports:
            - 10002:1234
            - 10003:10003

# Allow container to maintain proper node_modules
volumes:
  be-reserved:
    name: cah_be_node_modules
  fe-reserved-nm:
    name: cah_fe_node_modules
  fe-reserved-dist:
    name: cah_fe_dist

networks:
  full_stack_template:
    name: full_stack_template
